### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [trathailoi/gsrc-exercise#17]
Hello Loi 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions/concerns and share your opinions about the implementation (if any) during the process.

If we are aligned on any issue here and you’d like to correct them, please address the issue using proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. 😇

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding🤘

**Comment by olivierobert** [comment]
Loi, I completed the first round of reviews on my mind. First, the application is functional and contains all the required features. Second, I found a couple of significant architectural issues, made some suggestions, and raise questions. Have a check on the open issues.

**Comment by trathailoi** [comment]
Hello @olivierobert ,

Thank you for taking your time to look at my code and having such thoroughly feedback.

I will go through all those open issues and reply you before addressing them one by one.

**Comment by trathailoi** [comment]
Also, I’d like to share my opinions below on avoiding getting banned by Google because of mass-searching behavior. And I also would love to hear any suggestions from you.

- throttling the scraping jobs. This way is simple but not really great (and even risky if we set an inappropriate threshold metrics)
- scraping via proxies, with auto rotation. Potential solutions:
    - free proxies.
        - Pros: free.
        - Cons: unstable, slow
    - paid proxies.
        - Pros: stable, under control.
        - Cons: expensive
    - TOR
        - Pros: free, fast.
        - Cons: Google security check (I haven’t found any solution for this yet. I really love this solution, so if you have any idea on this one, please tell me 😊)
        - Also, with this approach, we can make it a micro service and scale it out into many instances (workers) which will run those scraping jobs in parallel. Throttling is no more a big deal, I think.
- potential features and functions that would make the product better:
    - failed jobs handling:
        - automatically retry in the background.
        - “search again” (manually retry) functionality on users’ end.

**Comment by trathailoi** [comment]
Hi @olivierobert , 

To avoid conflicts, I have to merge PRs myself, and it will automatically close issues. Please re-open the issues if they remain things. Thank you.

**Comment by olivierobert** [comment]
Regarding the workaround to scrap Google's search page, another solution is to use different [user agent headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) + having a random throttling between requests for each request is usually sufficient.

**Comment by trathailoi** [comment]
Thank you, I will try it out after this code review session.

**Comment by olivierobert** [comment]
Thank for working on the numerous fixes 🙏  It is now time to wrap up the code challenge review as we need to keep the whole process under a manageable timeline for all parties involved.
