### ISSUE TITLE
[Frontend] View Architecture

### ISSUE THREAD

**Issue by olivierobert** [trathailoi/gsrc-exercise#19]
## Issue

While the store library [Pinia](https://pinia.vuejs.org/) is used in the project, it is not fully leveraged. First, instead of having separate stores for each specific context, there is only the `rootStore`. There are even some authentication-related in it instead of being in an authentication store for instance:

https://github.com/trathailoi/gsrc-exercise/blob/08bb6434d92faa8bba3ab7e4122ac651d843a76e/src/stores/index.ts#L45-L58

Second, instead of using [actions](https://pinia.vuejs.org/core-concepts/actions.html) to decouple the views from API interactions and push data to the store, the API requests are defined in the views. Eventually, the views do not leverage components since they contain all the code to render in a single place. All of these result in tight coupling and complex code in views. 

## Expected

Views are composed of standalone components and use actions + stores to decouple API request handling.

**Comment by trathailoi** [comment]
Agreed. It was not a good architecture. I will address this issue.
