### ISSUE TITLE
[Improvement] Create an API Request Manager/Service

### ISSUE THREAD

**Issue by olivierobert** [trathailoi/gsrc-exercise#20]
## Issue

To make API requests, `axios` is used. However, the following code is duplicated in several places e.g., services, stores, views:

```
baseURL: `${import.meta.env.VITE_BASE_API || ''}${import.meta.env.VITE_BASE_API_VERSION || '/api/v1.0'}`
```

## Expected

There should be instead one manager/service module to define this in a single place. As a result, the following improvements can be added:
- Unify error handling including authentication errors, retries, etc.
- Abstraction of the usage of `axios` since it will be imported in a single place.
- Leverage [axios' interceptors](https://axios-http.com/docs/interceptors) for logging, for instance, and other use cases.

**Comment by trathailoi** [comment]
Agree. That would be cleaner. I will address this issue.
