### ISSUE TITLE
[Improvement] Low test coverage

### ISSUE THREAD

**Issue by olivierobert** [trathailoi/gsrc-exercise#22]
## Issue

While the README acknowledges the status of the test coverage, many parts of the codebase are not adequately covered. The frontend application does not have any tests 😅  As for the backend application, the keyword service has the most tests but there are no tests for `auth` and `scraper`. Both represent core business logic.

💡 Note that there might be a copy/pasting or typo issue with the following code as it refers to `movie` instead of `keyword`:

https://github.com/trathailoi/gsrc-exercise/blob/08bb6434d92faa8bba3ab7e4122ac651d843a76e/backend/src/keyword/keyword.service.spec.ts#L13

## Expected

The core business logic such as the scraper should be unit tested. The same goes for the views. The addition of integration tests for all API endpoints would be nice-to-have.

**Comment by trathailoi** [comment]
Sorry, my bad, I was doing this challenge in a rush. This repo was cloned from another repo of mine which I have been working on to learn NestJs. The typo is fixed and those missing unit tests are added. Please have a look on the [PR](https://github.com/trathailoi/gsrc-exercise/pull/28) (and the [coverage report](https://github.com/trathailoi/gsrc-exercise/pull/28#issuecomment-1106505990) as well).
